---
- hosts: webservers
  gather_facts: yes
  tasks:
   - name: Update apt cache
     become: yes
     apt:
      update_cache: yes
      cache_valid_time: 3600
   - name: Ensure nginx is installed
     become: yes
     apt:
      name: nginx
      state: latest
   - name: Install php-fpm
     become: yes
     apt:
      name: php7.4-fpm
      state: present
   - name: Start nginx
     become: yes
     service:
         name: nginx
         state: started
   - name: Copy the php file
     become: yes
     copy:
       src: templates/index.php
       dest: /var/www/html/
   - name: Add the template file
     become: yes
     template:
       src: templates/nginx.conf
       dest: /etc/nginx/sites-available/default
   - name: Enable the configuration file from nginx available sites
     become: yes
     file:
       src: /etc/nginx/sites-available/default
       dest: /etc/nginx/sites-enabled/default
       state: link
   - name: Restart Web Servers
     become: yes
     service:
          name: nginx
          state: restarted

- hosts: haproxy
  gather_facts: yes
  vars:
    haproxy_mode: http
    haproxy_algorithm: roundrobin
    haproxy_backend: Web_servers
  become: yes
  tasks:
   #- debug:
   #   var: vars.hostvars.devhaproxy
   #- debug:
   #   var: ansible_default_ipv4
   #   verbosity: 0
   - name: Update apt cache in Haproxy
     apt:
      update_cache: yes
      cache_valid_time: 3600
   - name: Install haproxy
     become: yes
     apt:
      name: haproxy
      state: present
   - name: Update HAProxy config file
     template:
      src: templates/haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
   - name: Restart HAProxy
     service:
       name: haproxy
       state: restarted
